version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-permissions
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
